require File.expand_path(File.dirname(__FILE__) + '/helper')

# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

limit = 4 * 1000 * 1000

# http://en.wikipedia.org/wiki/Fibonacci_number

clever_result = 0
index = 3
current = 2
while current < limit
  clever_result += current
  index += 3
  current = ProjectEulerHelper.get_fibonacci_by_index(index)
end

# checks that clever way gives same result as stupid way
stupid_result = 0
fibonacci = [0, 1]
while fibonacci.last < limit
  stupid_result += fibonacci.last if fibonacci.last % 2 == 0
  fibonacci << fibonacci.first + fibonacci.last
  fibonacci.shift
end

puts "Stupid result = #{stupid_result}"
puts "Clever result = #{clever_result}"